name: Notify Maintainer Merged PR
on:
  pull_request:
    types:
      - closed

jobs:
  notify-maintainer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Notify Maintainer
        if: github.event.pull_request.merged == true
        run: |
          echo "Pull request #${{ github.event.pull_request.number }} has been merged!" 
          echo "Notifying @${{ github.event.pull_request.user.login }}"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\":\"@${{ github.event.pull_request.user.login }}, your pull request #${{ github.event.pull_request.number }} has been merged!\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
